version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=horse_race_betting
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/horse_race_betting
      - REDIS_URL=redis://redis:6379/1
  
  celery:
    build: .
    command: celery -A horse_race_betting worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
