# Generated by Django 4.2.8 on 2023-12-11 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='horse',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.race'),
        ),
        migrations.AlterField(
            model_name='odds',
            name='odds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(default='Not Started', max_length=20),
        ),
    ]
